# Generated by Django 4.2.16 on 2026-05-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.PositiveSmallIntegerField()),
                (
                    "term",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Term 1"), (2, "Term 2"), (3, "Term 3")]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_schedules",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ("academic_year", "term"),
            },
        ),
        migrations.AddConstraint(
            model_name="termschedule",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year", "term"),
                name="unique_term_per_school_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="termschedule",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="term_end_after_start",
            ),
        ),
    ]
