# Generated by Django 4.2.16 on 2026-05-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_termschedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("ADMIN", "Administration"),
                            ("TECH", "Technical / ThutoTrack"),
                            ("ACAD", "Academic"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PROG", "In progress"),
                            ("DONE", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "response",
                    models.TextField(blank=True, help_text="Filled in by admin/HR"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to="core.teacherprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["school", "status"],
                        name="core_enquir_school__68bf6d_idx",
                    )
                ],
            },
        ),
    ]
