# Generated by Django 4.2.16 on 2026-05-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_teacherprofile_is_active_schooladminprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
                (
                    "selected_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_sessions",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["phone"], name="core_parent_phone_271797_idx")
                ],
            },
        ),
    ]
